"""add random tables

Revision ID: 059be8b6702b
Revises: c21fdb56229f
Create Date: 2021-10-02 14:01:18.562224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059be8b6702b'
down_revision = 'c21fdb56229f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_table',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_random_table_created_by_id_users')),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name=op.f('fk_random_table_edited_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_random_table'))
    )
    op.create_table('random_table_entry',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_random_table_entry_created_by_id_users')),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name=op.f('fk_random_table_entry_edited_by_id_users')),
    sa.ForeignKeyConstraint(['table_id'], ['random_table.id'], name=op.f('fk_random_table_entry_table_id_random_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_random_table_entry'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('random_table_entry')
    op.drop_table('random_table')
    # ### end Alembic commands ###
