"""add color to campaigns

Revision ID: 180afc4a79dd
Revises: dc0abafd4b9f
Create Date: 2020-03-24 19:16:24.967482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180afc4a79dd'
down_revision = 'dc0abafd4b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('color', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'color')
    # ### end Alembic commands ###
