"""add dice set

Revision ID: 202a5ec66d12
Revises: 059be8b6702b
Create Date: 2021-10-03 10:10:22.499003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202a5ec66d12'
down_revision = '059be8b6702b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dice_set',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('dice_string', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dice_set_created_by_id_users')),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name=op.f('fk_dice_set_edited_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dice_set'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dice_set')
    # ### end Alembic commands ###
