"""add moon colors

Revision ID: 33840467da5b
Revises: f10a621eab60
Create Date: 2019-01-05 16:05:14.261747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33840467da5b'
down_revision = 'f10a621eab60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('waning_color', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('waxing_color', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moons', schema=None) as batch_op:
        batch_op.drop_column('waxing_color')
        batch_op.drop_column('waning_color')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
