"""add visibility to char

Revision ID: 37a0a73fb09b
Revises: fde0a07012fb
Create Date: 2020-05-23 16:46:15.686846

"""
from alembic import op
import sqlalchemy as sa

from app import db
from app.character.models import Character

# revision identifiers, used by Alembic.
revision = '37a0a73fb09b'
down_revision = 'fde0a07012fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))
        batch_op.drop_column('dm_notes')

    with op.batch_alter_table('media_settings', schema=None) as batch_op:
        batch_op.drop_column('default_visible')

    # ### end Alembic commands ###

    chars = Character.query.all()

    for char in chars:
        char.is_visible = True

    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_visible', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dm_notes', sa.TEXT(), nullable=True))
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
