"""empty message

Revision ID: 3f69e0990764
Revises: 208d1d1ea595
Create Date: 2018-11-05 20:47:49.427963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f69e0990764'
down_revision = '208d1d1ea595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('filesize', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'filesize')
    # ### end Alembic commands ###
