"""add session_number

Revision ID: 44fb8dd89722
Revises: 4ca4f5fb810d
Create Date: 2020-04-25 15:59:05.943076

"""
from alembic import op
import sqlalchemy as sa
from app.campaign.models import Campaign


# revision identifiers, used by Alembic.
revision = '44fb8dd89722'
down_revision = '4ca4f5fb810d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###

    campaigns = Campaign.query.with_entities(Campaign.id).all()
    for campaign_id in campaigns:
        print(f"calculating session numbers for campaign {campaign_id}")

        op.execute(f"UPDATE sessions as a \
            SET session_number = (SELECT COUNT(*) FROM sessions AS b WHERE b.campaign_id = {campaign_id}\
            AND b.date < a.date) WHERE campaign_id = {campaign_id}")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('session_number')

    # ### end Alembic commands ###
