"""link sessions to campaigns

Revision ID: 4ca4f5fb810d
Revises: 180afc4a79dd
Create Date: 2020-03-24 20:54:47.175729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca4f5fb810d'
down_revision = '180afc4a79dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('campaign_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_sessions_campaign_id_campaigns'), 'campaigns', ['campaign_id'], ['id'])
        batch_op.drop_column('code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=3), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_sessions_campaign_id_campaigns'), type_='foreignkey')
    op.drop_column('sessions', 'campaign_id')
    # ### end Alembic commands ###
