"""add submap for map node

Revision ID: 4fde7abf7cc9
Revises: 73bb2c7b9372
Create Date: 2019-01-13 21:45:45.203904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fde7abf7cc9'
down_revision = '73bb2c7b9372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submap', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("map_nodes_sub_map", 'maps', ['submap'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_nodes', schema=None) as batch_op:
        batch_op.drop_constraint("map_nodes_sub_map", type_='foreignkey')
        batch_op.drop_column('submap')

    # ### end Alembic commands ###
