"""add map visibility option

Revision ID: 73bb2c7b9372
Revises: d25475c14b91
Create Date: 2019-01-13 21:32:44.497076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bb2c7b9372'
down_revision = 'd25475c14b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
