"""add user option: editor height

Revision ID: 77e07482a0b4
Revises: 8f5b2b817530
Create Date: 2019-04-10 20:48:36.724450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e07482a0b4'
down_revision = '8f5b2b817530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editor_height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('editor_height')

    # ### end Alembic commands ###
