"""add user.quicklinks option

Revision ID: 86ad44053205
Revises: f5ed086662b7
Create Date: 2019-05-18 21:16:07.133902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ad44053205'
down_revision = 'f5ed086662b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quicklinks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('quicklinks')

    # ### end Alembic commands ###
