"""add default map setting

Revision ID: 8f5b2b817530
Revises: 4fde7abf7cc9
Create Date: 2019-01-13 22:56:57.474298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5b2b817530'
down_revision = '4fde7abf7cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_map', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("map_default_map", 'maps', ['default_map'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_settings', schema=None) as batch_op:
        batch_op.drop_constraint("map_default_map", type_='foreignkey')
        batch_op.drop_column('default_map')

    # ### end Alembic commands ###
