"""add media sidebar user options

Revision ID: 8f912582b5f7
Revises: 990d40d5d709
Create Date: 2019-04-27 20:22:16.853287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f912582b5f7'
down_revision = '990d40d5d709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_direct_links', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('use_embedded_images', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('use_embedded_images')
        batch_op.drop_column('use_direct_links')

    # ### end Alembic commands ###
