"""add auditMixin to GeneralSetting

Revision ID: 990d40d5d709
Revises: e58833710b6e
Create Date: 2019-04-17 20:56:41.535994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990d40d5d709'
down_revision = 'e58833710b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edited_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_general_settings_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_general_settings_edited_by_id_users'), 'users', ['edited_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_general_settings_edited_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_general_settings_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('edited_by_id')
        batch_op.drop_column('edited')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
