"""add usersetting 'theme'

Revision ID: 9f16b43cdc83
Revises: 202a5ec66d12
Create Date: 2022-04-22 20:22:39.772606

"""
from alembic import op
import sqlalchemy as sa

from app.helpers import Theme


# revision identifiers, used by Alembic.
revision = '9f16b43cdc83'
down_revision = '202a5ec66d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.Integer(), nullable=True))

    # ### end Alembic commands ###

    op.execute(f"UPDATE users SET theme = {Theme.System.value}")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
