"""remove default_vis from events

Revision ID: a76ca5da1953
Revises: 37a0a73fb09b
Create Date: 2020-05-23 21:53:19.340547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76ca5da1953'
down_revision = '37a0a73fb09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_settings', schema=None) as batch_op:
        batch_op.drop_column('default_visible')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_visible', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
