"""remove dm notes from party

Revision ID: b0ecdd58f5f8
Revises: e5ef7453e724
Create Date: 2020-05-24 09:27:29.411962

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b0ecdd58f5f8'
down_revision = 'e5ef7453e724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_column('dm_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dm_notes', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
