"""add campaign party assoc

Revision ID: c21fdb56229f
Revises: c0461f0fafbb
Create Date: 2021-03-23 21:14:03.519823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21fdb56229f'
down_revision = 'c0461f0fafbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_party_assoc',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_party_assoc_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_campaign_party_assoc_party_id_parties'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_party_assoc')
    # ### end Alembic commands ###
