"""drop max filesize

Revision ID: cac89e217f3e
Revises: ee193fa91c72
Create Date: 2019-01-01 20:25:49.073876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac89e217f3e'
down_revision = 'ee193fa91c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_settings', schema=None) as batch_op:
        batch_op.drop_column('max_filesize')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_filesize', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
