"""add Map.name

Revision ID: ce5ea005ceea
Revises: 5c29b8bf9f35
Create Date: 2019-01-07 22:45:46.817817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5ea005ceea'
down_revision = '5c29b8bf9f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
