"""add map foreign key to MapNode

Revision ID: d25475c14b91
Revises: ce5ea005ceea
Create Date: 2019-01-13 18:09:22.376894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25475c14b91'
down_revision = 'ce5ea005ceea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_map', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("node_to_map", 'maps', ['on_map'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_nodes', schema=None) as batch_op:
        batch_op.drop_constraint("node_to_map", type_='foreignkey')
        batch_op.drop_column('on_map')

    # ### end Alembic commands ###
