"""add campaign table

Revision ID: dc0abafd4b9f
Revises: 86ad44053205
Create Date: 2020-03-23 22:21:46.289217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0abafd4b9f'
down_revision = '86ad44053205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dm_id', sa.Integer(), nullable=True),
    sa.Column('dm_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_campaigns_created_by_id_users')),
    sa.ForeignKeyConstraint(['dm_id'], ['users.id'], name=op.f('fk_campaigns_dm_id_users')),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name=op.f('fk_campaigns_edited_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('campaign_character_assoc',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_character_assoc_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_campaign_character_assoc_character_id_characters'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_character_assoc')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
