"""empty message

Revision ID: e0891392a2d3
Revises: 3f69e0990764
Create Date: 2018-12-09 22:34:52.740248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0891392a2d3'
down_revision = '3f69e0990764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('media_settings', 'max_filesize')
    op.add_column('general_settings', sa.Column('use_cdn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('media_settings', sa.Column('max_filesize', sa.INTEGER(), nullable=True))
    op.drop_column('general_settings', 'use_cdn')
    # ### end Alembic commands ###
