"""add use_cdn setting

Revision ID: e0891392a2d3
Revises: 3f69e0990764
Create Date: 2018-12-09 22:34:52.740248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0891392a2d3'
down_revision = '3f69e0990764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_cdn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('use_cdn')
    # ### end Alembic commands ###
