"""remove title from general settings

Revision ID: e5ef7453e724
Revises: a76ca5da1953
Create Date: 2020-05-23 22:12:13.897435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ef7453e724'
down_revision = 'a76ca5da1953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
