"""add moons

Revision ID: ee193fa91c72
Revises: 2eafb8addf89
Create Date: 2018-12-31 22:27:29.230678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee193fa91c72'
down_revision = '2eafb8addf89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase_length', sa.Integer(), nullable=True),
    sa.Column('phase_offset', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moons')
    # ### end Alembic commands ###
