"""remove obsolete GeneralSetting, add char.private_notes

Revision ID: f10a621eab60
Revises: cac89e217f3e
Create Date: 2019-01-01 21:38:23.618600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10a621eab60'
down_revision = 'cac89e217f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('use_cdn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_cdn', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('private_notes')

    # ### end Alembic commands ###
