"""add map setting 'check_interval'

Revision ID: fd67b6ffe895
Revises: 0d9c278ed883
Create Date: 2019-01-06 14:22:11.665143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd67b6ffe895'
down_revision = '0d9c278ed883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_interval', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_settings', schema=None) as batch_op:
        batch_op.drop_column('check_interval')

    # ### end Alembic commands ###
