"""simplify roles

Revision ID: fde0a07012fb
Revises: b1d25db65c20
Create Date: 2020-05-21 17:01:07.887247

"""
from alembic import op
import sqlalchemy as sa

from app import db
from app.user.models import User
from app.helpers import Role

# revision identifiers, used by Alembic.
revision = 'fde0a07012fb'
down_revision = 'b1d25db65c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_name')

    op.drop_table('roles')
    op.drop_table('user_role_assoc')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_sessions_campaign_id_campaigns'), 'campaigns', ['campaign_id'], ['id'])
        batch_op.drop_column('code')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))

    users = User.query.all()

    for user in users:
        if user.id == 1:
            user.role = Role.Admin.value
        else:
            user.role = Role.User.value
    db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=3), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_sessions_campaign_id_campaigns'), type_='foreignkey')

    op.create_table('user_role_assoc',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('ix_roles_name', ['name'], unique=1)

    # ### end Alembic commands ###
